In [1]:
import numpy as np

In [3]:
a = np.array([[2,3,4,5,],[6,7,8,9,]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [8]:
print(a[1,2])

8


In [9]:
print(a[0,:])

[2 3 4 5]


In [10]:
print(a[:,2])

[4 8]
