In [1]:
import numpy as np

In [3]:
# array 1D
d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [4]:
d1.shape

(3,)

In [5]:
d1.ndim

1

In [6]:
d1.dtype

dtype('int64')

In [8]:
d2 = np.array([[1,2,3],[4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [13]:
d3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
